#!/usr/bin/env python3
"""
generate_report.py — one-page executive-summary PDF (SIH outcome i).

Usage:
    python generate_report.py --data model_data --out model_data/risk_report.pdf
"""

import argparse
import datetime as dt
import json
import os

import pandas as pd
from fpdf import FPDF, XPos, YPos

from feature_labels import human_label, combined_importance

BLUE = (26, 35, 126)
ORANGE = (255, 111, 0)
GREY = (90, 90, 90)


def month_label(report_month):
    return dt.datetime.strptime(report_month, "%Y-%m").strftime("%B %Y")


def build_pdf(summary, top10, top_drivers, out_path):
    pdf = FPDF(format="A4")
    pdf.add_page()
    pdf.set_margin(12)

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*BLUE)
    pdf.cell(0, 10, f"PAIMANA-AI Monthly Risk Report -- {month_label(summary['report_month'])}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*ORANGE)
    pdf.cell(0, 6, "AI-powered infrastructure project monitoring | SIH26103", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*BLUE)
    pdf.line(12, pdf.get_y() + 2, 198, pdf.get_y() + 2)
    pdf.ln(6)

    # Section 1 — portfolio snapshot
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "1. Portfolio Snapshot", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Total projects tracked: {summary['total_projects']:,}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, (f"Risk bands -- Red: {summary['red']}  |  Amber: {summary['amber']}  |  "
                     f"Green: {summary['green']}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Section 2 — top 10 riskiest
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "2. Top 10 Riskiest Projects", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*BLUE)
    pdf.set_text_color(255, 255, 255)
    widths = [110, 25, 25, 26]
    for w, h in zip(widths, ["Project", "Risk Score", "Slip Prob", "Cost Prob"]):
        pdf.cell(w, 6, h, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(20, 20, 20)
    for _, r in top10.iterrows():
        name = r.project_name if isinstance(r.project_name, str) else "(unnamed)"
        pdf.cell(widths[0], 6, name[:70], border=1)
        pdf.cell(widths[1], 6, f"{r.risk_score:.1f}", border=1, align="C")
        pdf.cell(widths[2], 6, f"{r.slip_prob:.0%}", border=1, align="C")
        pdf.cell(widths[3], 6, f"{r.cost_prob:.0%}", border=1, align="C")
        pdf.ln()
    pdf.ln(3)

    # Section 3 — alerts
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "3. Early Warning Alerts", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    a = summary["alerts"]
    pdf.cell(0, 6, (f"Rapidly Deteriorating: {a['rapidly_deteriorating']}  |  "
                     f"Newly At Risk: {a['newly_at_risk']}  |  "
                     f"Stalled and Overdue: {a['stalled_and_overdue']}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Section 4 — drivers
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "4. Top 5 Cost & Time Overrun Drivers (SHAP)", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    for i, feat in enumerate(top_drivers, start=1):
        pdf.cell(0, 6, f"{i}. {feat}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Footer
    pdf.set_y(-18)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    ts = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    pdf.cell(0, 6, f"Generated by PAIMANA-AI | SIH26103 | {ts}", align="C")

    pdf.output(out_path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="model_data")
    ap.add_argument("--out", default="model_data/risk_report.pdf")
    args = ap.parse_args()

    with open(os.path.join(args.data, "risk_summary.json"), encoding="utf-8") as f:
        summary = json.load(f)
    risk = pd.read_csv(os.path.join(args.data, "risk_scores.csv"))
    top10 = risk.nlargest(10, "risk_score")

    shap_path = os.path.join(args.data, "shap_global.csv")
    if os.path.exists(shap_path):
        sg = pd.read_csv(shap_path)
        sg = combined_importance(sg)
        top_drivers = [human_label(f) for f in sg.sort_values("combined", ascending=False).head(5).feature]
    else:
        top_drivers = ["(run explain_risks.py first for SHAP drivers)"]

    build_pdf(summary, top10, top_drivers, args.out)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
