"""initial schema

Revision ID: 484541b31599
Revises: 
Create Date: 2026-09-04 00:28:53.083083

"""
from alembic import op
import sqlalchemy as sa


revision = '484541b31599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dim', sa.String(), nullable=False),
    sa.Column('dim_value', sa.String(), nullable=False),
    sa.Column('report_month', sa.String(), nullable=False),
    sa.Column('pct_on_budget', sa.Float(), nullable=True),
    sa.Column('pct_on_time', sa.Float(), nullable=True),
    sa.Column('n_projects', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('ministry', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('original_cost', sa.Float(), nullable=True),
    sa.Column('latest_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ministry_scope', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('report_month', sa.String(), nullable=False),
    sa.Column('driver_rank', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('feature_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('report_month', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('report_month', sa.String(), nullable=False),
    sa.Column('physical_progress', sa.Float(), nullable=True),
    sa.Column('slip_prob', sa.Float(), nullable=True),
    sa.Column('cost_prob', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('risk_score_delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###

    # Seed a single placeholder officer row -- spec requires a seeded users row,
    # no login screen yet.
    op.execute(
        "INSERT INTO users (name, role) VALUES ('Officer', 'officer')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    op.drop_table('risk_history')
    op.drop_table('risk_drivers')
    op.drop_table('action_log')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
